name: Code Analysis
on:
  push:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Create empty local.properties
        run: |
          echo "key.store=dummy" > local.properties
          echo "key.storePassword=dummy" >> local.properties
          echo "key.alias=dummy" >> local.properties
          echo "key.password=dummy" >> local.properties
          
      - name: ktlint
        shell: bash
        run: ./gradlew ktlintCheck
        
      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
