name: Unit Tests
on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      
      - name: Create empty local.properties
        run: |
          echo "key.store=dummy" > local.properties
          echo "key.storePassword=dummy" >> local.properties
          echo "key.alias=dummy" >> local.properties
          echo "key.password=dummy" >> local.properties

      - name: Execute Gradle command - testDebugUnitTest
        run: ./gradlew testDebugUnitTest
